version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - backend
    command: openssl req -x509 -newkey rsa:4096 -sha256 -days 185 -nodes -keyout obminyashka.key -out obminyashka.crt -subj "/CN=localhost"

  web-server:
    image: web-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/evo_exchange?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_SSL_KEY_STORE_PASSWORD: root
      SERVER_SSL_KEY_STORE: keystore.p12
      APP_JWT_SECRET: root
    command: mvn clean spring-boot:run
    depends_on:
      - database
      - nginx
    networks:
      - backend

  database:
    image: mysql:latest
    command: 'mysqld --default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: evo_exchange
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge