version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/certs/:/etc/ssl/certs/
    networks:
      - containers-network

  web-server:
    image: web-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/evo_exchange?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_SSL_KEY_STORE_PASSWORD: root
      SERVER_SSL_KEY_STORE: keystore.p12
      APP_JWT_SECRET: root
    command: mvn clean spring-boot:run
    volumes:
      - ./nginx/certs/keystore.p12:/tmp/keystore.p12
    depends_on:
      - database
    networks:
      - containers-network

  database:
    image: mysql:latest
    command: 'mysqld --default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: evo_exchange
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    restart: always
    networks:
      - containers-network

networks:
  containers-network:
    driver: bridge